export const PERMS = {
    item_view: "ITEM_VIEW",
    dealer_item_view: "DEALER_ITEM_VIEW",
    view_org_members: "ORG_MEMBER_VIEW",
    manage_org_members: "ORG_MEMBER_MANAGE",
    manage_org_role: "ORG_ROLE_MANAGE",
    view_org_role: "ORG_ROLE_VIEW",
    view_dealer_members: "VIEW_DEALER_MEMBER",
    manage_dealer_members: "MANAGE_DEALER_MEMBER",
    create_dealer: "DEALER_CREATE",
    manage_dealer_role: "MANAGE_DEALER_ROLE",
    view_dealer_role: "VIEW_DEALER_ROLE",
    dealers_view: "DEALER_VIEW",
    manage_storage: "STORAGE_MANAGE",
    item_setting_view: "VIEW_ITEM_SETTING",
    manage_item_setting: "MANAGE_ITEM_SETTING",
    manage_items: "MANAGE_ITEMS",
    item_accept: "ACCEPT_ITEMS",
    item_accept_history_view: "ACCEPT_ITEMS_VIEW",
    customers_view: "CUSTOMERS_VIEW",
    manage_customers: "MANAGE_CUSTOMERS"
} as const;